# Generated by Django 5.2.7 on 2025-10-23 19:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(blank=True, choices=[(None, '(Unspecified)'), ('UNK', 'UNSPECIFIED'), ('MEL', 'MELEE'), ('VCL', 'VERY CLOSE'), ('CLO', 'CLOSE'), ('FAR', 'FAR'), ('VFA', 'VERY FAR')], default='UNK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Adversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tier', models.PositiveSmallIntegerField(blank=True, choices=[(None, '(Unspecified)'), (0, 'UNSPECIFIED'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], db_column='tier', default=0)),
                ('type', models.CharField(blank=True, choices=[(None, '(Unspecified)'), ('UNK', 'UNSPECIFIED'), ('BRU', 'BRUISER'), ('HOR', 'HORDE'), ('LEA', 'LEADER'), ('MIN', 'MINION'), ('RAN', 'RANGED'), ('SKU', 'SKULK'), ('SOC', 'SOCIAL'), ('SOL', 'SOLO'), ('STA', 'STANDARD'), ('SUP', 'SUPPORT')], db_column='type', default='UNK', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('threshold_major', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('threshold_severe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit_point', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horde_hit_point', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress_point', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('atk_bonus', models.SmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[(None, '(Unspecified)'), ('UNK', 'UNSPECIFIED'), ('DRA', 'DRAFT'), ('PUB', 'PUBLISHED')], db_column='status', db_index=True, default='UNK', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('basic_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adversaries.basicattack')),
            ],
            options={
                'verbose_name_plural': 'Adversaries',
            },
        ),
        migrations.CreateModel(
            name='DamageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_number', models.PositiveSmallIntegerField(default=0, help_text='0 dice means flat damage', validators=[django.core.validators.MinValueValidator(0)])),
                ('dice_type', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.SmallIntegerField(default=0)),
                ('damage_type', models.CharField(blank=True, choices=[(None, '(Unspecified)'), ('UNK', 'UNSPECIFIED'), ('PHY', 'PHYSICAL'), ('MAG', 'MAGICAL'), ('BTH', 'BOTH')], default='UNK', max_length=3)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dice_number', 0), ('dice_type', 0), ('bonus__gte', 0)), models.Q(('dice_number__gte', 1), ('dice_type__gte', 2)), _connector='OR'), name='dp_valid_shape'), models.UniqueConstraint(fields=('dice_number', 'dice_type', 'bonus', 'damage_type'), name='damage_profile_value_object')],
            },
        ),
        migrations.AddField(
            model_name='basicattack',
            name='damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_attack', to='adversaries.damageprofile'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_experience_value_object')],
            },
        ),
        migrations.CreateModel(
            name='AdversaryExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.SmallIntegerField(default=0)),
                ('adversary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversary_experiences', to='adversaries.adversary')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversary_experiences', to='adversaries.experience')),
            ],
        ),
        migrations.AddField(
            model_name='adversary',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='adversaries', through='adversaries.AdversaryExperience', to='adversaries.experience'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[(None, '(Unspecified)'), ('UNK', 'UNSPECIFIED'), ('PAS', 'PASSIVE'), ('ACT', 'ACTION'), ('REA', 'REACTION')], default='UNK', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'type', 'description'), name='feature_entity')],
            },
        ),
        migrations.AddField(
            model_name='adversary',
            name='features',
            field=models.ManyToManyField(blank=True, to='adversaries.feature'),
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_tactic_value_object')],
            },
        ),
        migrations.AddField(
            model_name='adversary',
            name='tactics',
            field=models.ManyToManyField(blank=True, to='adversaries.tactic'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_tag_value_object')],
            },
        ),
        migrations.AddField(
            model_name='adversary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='adversaries.tag'),
        ),
        migrations.AddConstraint(
            model_name='basicattack',
            constraint=models.UniqueConstraint(fields=('name', 'range', 'damage'), name='basic_attack_value_object'),
        ),
        migrations.AddConstraint(
            model_name='adversaryexperience',
            constraint=models.UniqueConstraint(fields=('adversary', 'experience'), name='unique_adversary_experience'),
        ),
        migrations.AddIndex(
            model_name='adversary',
            index=models.Index(fields=['name'], name='adversaries_name_67125c_idx'),
        ),
        migrations.AddIndex(
            model_name='adversary',
            index=models.Index(fields=['type', 'tier'], name='adversaries_type_dcaeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='adversary',
            index=models.Index(fields=['status'], name='adversaries_status_26bf76_idx'),
        ),
        migrations.AddConstraint(
            model_name='adversary',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='adversary_entity'),
        ),
        migrations.AddConstraint(
            model_name='adversary',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='adversary_name_not_empty'),
        ),
    ]
