# Generated by Django 5.2.7 on 2025-10-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adversaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversary',
            name='atk_bonus',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='basic_attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adversaries.basicattack'),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='difficulty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='experiences',
            field=models.ManyToManyField(related_name='adversaries', through='adversaries.AdversaryExperience', to='adversaries.experience'),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='features',
            field=models.ManyToManyField(to='adversaries.feature'),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='hit_point',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='horde_hit_point',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='stress_point',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='tactics',
            field=models.ManyToManyField(null=True, to='adversaries.tactic'),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='tags',
            field=models.ManyToManyField(null=True, to='adversaries.tag'),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='threshold_major',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adversary',
            name='threshold_severe',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
