# Generated by Django 5.2.7 on 2025-10-22 12:55

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adversaries', '0002_alter_adversary_atk_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adversary',
            name='unique_author_name',
        ),
        migrations.RemoveConstraint(
            model_name='basicattack',
            name='basic_attack_entity',
        ),
        migrations.RemoveConstraint(
            model_name='damageprofile',
            name='damage_profile_entity',
        ),
        migrations.AddConstraint(
            model_name='adversary',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='adversary_entity'),
        ),
        migrations.AddConstraint(
            model_name='basicattack',
            constraint=models.UniqueConstraint(fields=('name', 'range', 'damage'), name='basic_attack_value_object'),
        ),
        migrations.AddConstraint(
            model_name='damageprofile',
            constraint=models.UniqueConstraint(fields=('dice_number', 'dice_type', 'bonus', 'damage_type'), name='damage_profile_value_object'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_experience_value_object'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'description'), name='feature_entity'),
        ),
        migrations.AddConstraint(
            model_name='tactic',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_tactic_value_object'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_tag_value_object'),
        ),
    ]
